vppConfig:
  interfaces:
    # Loopback interface (Example)
    - name: "loop1"
      type: SOFTWARE_LOOPBACK
      enabled: true
      ipAddresses:
    
    # Gigabit Ethernet Interface
    - name: "GigabitEthernet0/13/0"
      type: ETHERNET
      enabled: true
      mtu: 1500
      ipAddresses:
        - 172.93.110.120/24  # Example IP address, replace with actual IP if needed

    # GRE Tunnel Interface
    - name: "gre1"
      type: GRE_TUNNEL
      enabled: true
      gre:
        srcAddr: 172.93.110.120   # Local tunnel endpoint in a different subnet
        dstAddr: 45.76.226.112   # Remote tunnel endpoint in a different subnet
        tunnelType: L3           # Layer 3 GRE Tunnel
      ipAddresses:
        - 10.10.10.1/30          # IP Address of GRE Tunnel

  # Define Static Routes to Forward Specific /32 IPs Through GRE Tunnel
  routes:
    - destinationSubnet: 103.195.102.92/24   # Route specific IP through GRE tunnel
      nextHopAddr: 10.10.10.2              # Peer IP inside GRE Tunnel
      outgoingInterface: "gre1"            # Use GRE tunnel for forwarding